# Generated by Django 5.0.3 on 2024-03-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0003_alter_corredor_coes_dsc_alter_posicao_poes_dsc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corredor',
            name='loes_id',
        ),
        migrations.RemoveField(
            model_name='corredor',
            name='sles_id',
        ),
        migrations.RemoveField(
            model_name='posicao',
            name='coes_id',
        ),
        migrations.RemoveField(
            model_name='posicao',
            name='loes_id',
        ),
        migrations.RemoveField(
            model_name='posicao',
            name='pres_id',
        ),
        migrations.RemoveField(
            model_name='posicao',
            name='sles_id',
        ),
        migrations.RemoveField(
            model_name='prateleira',
            name='coes_id',
        ),
        migrations.RemoveField(
            model_name='prateleira',
            name='loes_id',
        ),
        migrations.RemoveField(
            model_name='prateleira',
            name='sles_id',
        ),
    ]
