# Generated by Django 5.0.3 on 2024-03-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0005_alter_corredor_coes_dsc_alter_posicao_poes_dsc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prateleira',
            options={'verbose_name': 'Prateleira', 'verbose_name_plural': 'Prateleiras'},
        ),
    ]
